name: CD Pipeline

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Ambiente para implantação'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - test
        - prod
      version:
        description: 'Versão para implantação (apenas para prod)'
        required: false
        default: 'latest'

jobs:
  deploy-dev:
    if: github.event.inputs.environment == 'dev' || (github.ref == 'refs/heads/develop' && github.event_name == 'push')
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    # Configurar QEMU para suporte a múltiplas plataformas
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    # Configurar Docker Buildx com mais opções
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true
        version: latest
    
    # Verificar se os segredos do Docker Hub estão configurados
    - name: Check Docker Hub secrets
      id: check-secrets
      run: |
        if [ -n "${{ secrets.DOCKERHUB_USERNAME }}" ] && [ -n "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
          echo "SECRETS_AVAILABLE=true" >> $GITHUB_OUTPUT
        else
          echo "SECRETS_AVAILABLE=false" >> $GITHUB_OUTPUT
          echo "::warning::Docker Hub secrets not configured. Skipping push to Docker Hub."
        fi
    
    # Login no Docker Hub (apenas se os segredos estiverem disponíveis)
    - name: Login to Docker Hub
      if: steps.check-secrets.outputs.SECRETS_AVAILABLE == 'true'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # Preparar o diretório vendor para o frontend
    - name: Prepare vendor directory for frontend
      run: |
        cd frontend
        go mod vendor
    
    # Construir imagem da API
    - name: Build API Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./api
        file: ./api/Dockerfile
        push: ${{ steps.check-secrets.outputs.SECRETS_AVAILABLE == 'true' }}
        load: ${{ steps.check-secrets.outputs.SECRETS_AVAILABLE != 'true' }}
        tags: ${{ secrets.DOCKERHUB_USERNAME || 'local' }}/ci-cd-demo-api:develop
        cache-from: type=gha
        cache-to: type=gha,mode=max
        provenance: false
        platforms: linux/amd64
    
    # Construir imagem do Frontend
    - name: Build Frontend Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: ${{ steps.check-secrets.outputs.SECRETS_AVAILABLE == 'true' }}
        load: ${{ steps.check-secrets.outputs.SECRETS_AVAILABLE != 'true' }}
        tags: ${{ secrets.DOCKERHUB_USERNAME || 'local' }}/ci-cd-demo-frontend:develop
        cache-from: type=gha
        cache-to: type=gha,mode=max
        provenance: false
        platforms: linux/amd64
    
    # Simular deploy para ambiente de desenvolvimento
    - name: Deploy to Development Environment
      run: |
        echo "Deploying to development environment..."
        echo "API image: ${{ secrets.DOCKERHUB_USERNAME || 'local' }}/ci-cd-demo-api:develop"
        echo "Frontend image: ${{ secrets.DOCKERHUB_USERNAME || 'local' }}/ci-cd-demo-frontend:develop"
    
    # Criar arquivo docker-compose para ambiente de desenvolvimento
    - name: Create docker-compose.dev.yml
      run: |
        cat > docker-compose.dev.yml << EOL
        version: '3.8'
        
        services:
          api:
            image: ${{ secrets.DOCKERHUB_USERNAME || 'local' }}/ci-cd-demo-api:develop
            container_name: ci-cd-demo-api
            ports:
              - "8080:8080"
            networks:
              - ci-cd-network
            healthcheck:
              test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
              interval: 30s
              timeout: 10s
              retries: 3
              start_period: 10s
        
          frontend:
            image: ${{ secrets.DOCKERHUB_USERNAME || 'local' }}/ci-cd-demo-frontend:develop
            container_name: ci-cd-demo-frontend
            ports:
              - "3000:3000"
            depends_on:
              - api
            environment:
              - API_URL=http://api:8080
            networks:
              - ci-cd-network
            healthcheck:
              test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
              interval: 30s
              timeout: 10s
              retries: 3
              start_period: 10s
        
        networks:
          ci-cd-network:
            driver: bridge
        EOL
    
    # Salvar o arquivo docker-compose como artefato
    - name: Upload docker-compose.dev.yml as artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-compose-dev
        path: docker-compose.dev.yml
        retention-days: 7
  
  deploy-test:
    if: github.event.inputs.environment == 'test'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    # Configurar QEMU para suporte a múltiplas plataformas
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    # Configurar Docker Buildx com mais opções
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true
        version: latest
    
    # Verificar se os segredos do Docker Hub estão configurados
    - name: Check Docker Hub secrets
      id: check-secrets
      run: |
        if [ -n "${{ secrets.DOCKERHUB_USERNAME }}" ] && [ -n "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
          echo "SECRETS_AVAILABLE=true" >> $GITHUB_OUTPUT
        else
          echo "SECRETS_AVAILABLE=false" >> $GITHUB_OUTPUT
          echo "::warning::Docker Hub secrets not configured. Skipping push to Docker Hub."
        fi
    
    # Login no Docker Hub (apenas se os segredos estiverem disponíveis)
    - name: Login to Docker Hub
      if: steps.check-secrets.outputs.SECRETS_AVAILABLE == 'true'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # Preparar o diretório vendor para o frontend
    - name: Prepare vendor directory for frontend
      run: |
        cd frontend
        go mod vendor
    
    # Construir imagem da API
    - name: Build API Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./api
        file: ./api/Dockerfile
        push: ${{ steps.check-secrets.outputs.SECRETS_AVAILABLE == 'true' }}
        load: ${{ steps.check-secrets.outputs.SECRETS_AVAILABLE != 'true' }}
        tags: ${{ secrets.DOCKERHUB_USERNAME || 'local' }}/ci-cd-demo-api:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
        provenance: false
        platforms: linux/amd64
    
    # Construir imagem do Frontend
    - name: Build Frontend Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: ${{ steps.check-secrets.outputs.SECRETS_AVAILABLE == 'true' }}
        load: ${{ steps.check-secrets.outputs.SECRETS_AVAILABLE != 'true' }}
        tags: ${{ secrets.DOCKERHUB_USERNAME || 'local' }}/ci-cd-demo-frontend:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
        provenance: false
        platforms: linux/amd64
    
    # Simular deploy para ambiente de teste
    - name: Deploy to Test Environment
      run: |
        echo "Deploying to test environment..."
        echo "API image: ${{ secrets.DOCKERHUB_USERNAME || 'local' }}/ci-cd-demo-api:test"
        echo "Frontend image: ${{ secrets.DOCKERHUB_USERNAME || 'local' }}/ci-cd-demo-frontend:test"
    
    # Criar arquivo docker-compose para ambiente de teste
    - name: Create docker-compose.test.yml
      run: |
        cat > docker-compose.test.yml << EOL
        version: '3.8'
        
        services:
          api:
            image: ${{ secrets.DOCKERHUB_USERNAME || 'local' }}/ci-cd-demo-api:test
            container_name: ci-cd-demo-api
            ports:
              - "8080:8080"
            networks:
              - ci-cd-network
            healthcheck:
              test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
              interval: 30s
              timeout: 10s
              retries: 3
              start_period: 10s
        
          frontend:
            image: ${{ secrets.DOCKERHUB_USERNAME || 'local' }}/ci-cd-demo-frontend:test
            container_name: ci-cd-demo-frontend
            ports:
              - "3000:3000"
            depends_on:
              - api
            environment:
              - API_URL=http://api:8080
            networks:
              - ci-cd-network
            healthcheck:
              test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
              interval: 30s
              timeout: 10s
              retries: 3
              start_period: 10s
        
        networks:
          ci-cd-network:
            driver: bridge
        EOL
    
    # Salvar o arquivo docker-compose como artefato
    - name: Upload docker-compose.test.yml as artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-compose-test
        path: docker-compose.test.yml
        retention-days: 7
  
  deploy-prod:
    if: github.event.inputs.environment == 'prod' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    # Configurar QEMU para suporte a múltiplas plataformas
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    # Configurar Docker Buildx com mais opções
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true
        version: latest
    
    # Verificar se os segredos do Docker Hub estão configurados
    - name: Check Docker Hub secrets
      id: check-secrets
      run: |
        if [ -n "${{ secrets.DOCKERHUB_USERNAME }}" ] && [ -n "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
          echo "SECRETS_AVAILABLE=true" >> $GITHUB_OUTPUT
        else
          echo "SECRETS_AVAILABLE=false" >> $GITHUB_OUTPUT
          echo "::warning::Docker Hub secrets not configured. Skipping push to Docker Hub."
        fi
    
    # Definir a versão
    - name: Set version tag
      id: set-version
      run: |
        if [ "${{ github.event.inputs.version }}" != "" ] && [ "${{ github.event.inputs.version }}" != "latest" ]; then
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
        else
          echo "VERSION=latest" >> $GITHUB_OUTPUT
        fi
    
    # Login no Docker Hub (apenas se os segredos estiverem disponíveis)
    - name: Login to Docker Hub
      if: steps.check-secrets.outputs.SECRETS_AVAILABLE == 'true'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # Preparar o diretório vendor para o frontend
    - name: Prepare vendor directory for frontend
      run: |
        cd frontend
        go mod vendor
    
    # Construir imagem da API
    - name: Build API Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./api
        file: ./api/Dockerfile
        push: ${{ steps.check-secrets.outputs.SECRETS_AVAILABLE == 'true' }}
        load: ${{ steps.check-secrets.outputs.SECRETS_AVAILABLE != 'true' }}
        tags: ${{ secrets.DOCKERHUB_USERNAME || 'local' }}/ci-cd-demo-api:${{ steps.set-version.outputs.VERSION }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        provenance: false
        platforms: linux/amd64
    
    # Construir imagem do Frontend
    - name: Build Frontend Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: ${{ steps.check-secrets.outputs.SECRETS_AVAILABLE == 'true' }}
        load: ${{ steps.check-secrets.outputs.SECRETS_AVAILABLE != 'true' }}
        tags: ${{ secrets.DOCKERHUB_USERNAME || 'local' }}/ci-cd-demo-frontend:${{ steps.set-version.outputs.VERSION }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        provenance: false
        platforms: linux/amd64
    
    # Simular deploy para ambiente de produção
    - name: Deploy to Production Environment
      run: |
        echo "Deploying to production environment with version ${{ steps.set-version.outputs.VERSION }}..."
        echo "API image: ${{ secrets.DOCKERHUB_USERNAME || 'local' }}/ci-cd-demo-api:${{ steps.set-version.outputs.VERSION }}"
        echo "Frontend image: ${{ secrets.DOCKERHUB_USERNAME || 'local' }}/ci-cd-demo-frontend:${{ steps.set-version.outputs.VERSION }}"
    
    # Criar arquivo docker-compose para ambiente de produção
    - name: Create docker-compose.prod.yml
      run: |
        cat > docker-compose.prod.yml << EOL
        version: '3.8'
        
        services:
          api:
            image: ${{ secrets.DOCKERHUB_USERNAME || 'local' }}/ci-cd-demo-api:${{ steps.set-version.outputs.VERSION }}
            container_name: ci-cd-demo-api
            ports:
              - "8080:8080"
            networks:
              - ci-cd-network
            restart: always
            healthcheck:
              test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
              interval: 30s
              timeout: 10s
              retries: 3
              start_period: 10s
        
          frontend:
            image: ${{ secrets.DOCKERHUB_USERNAME || 'local' }}/ci-cd-demo-frontend:${{ steps.set-version.outputs.VERSION }}
            container_name: ci-cd-demo-frontend
            ports:
              - "3000:3000"
            depends_on:
              - api
            environment:
              - API_URL=http://api:8080
            networks:
              - ci-cd-network
            restart: always
            healthcheck:
              test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
              interval: 30s
              timeout: 10s
              retries: 3
              start_period: 10s
        
        networks:
          ci-cd-network:
            driver: bridge
        EOL
    
    # Salvar o arquivo docker-compose como artefato
    - name: Upload docker-compose.prod.yml as artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-compose-prod
        path: docker-compose.prod.yml
        retention-days: 7 