name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  # Para permitir execução manual
  workflow_dispatch:

jobs:
  test-api:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true
    
    - name: Install dependencies for API
      run: |
        cd api
        go mod download
    
    - name: Run tests for API
      run: |
        cd api
        go test -v ./...
  
  test-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true
    
    - name: Install dependencies for Frontend
      run: |
        cd frontend
        go mod download
    
    - name: Run tests for Frontend
      run: |
        cd frontend
        go test -v ./...
  
  build-images:
    runs-on: ubuntu-latest
    needs: [test-api, test-frontend]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build API Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./api
        push: false
        tags: ci-cd-demo-api:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Build Frontend Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        push: false
        tags: ci-cd-demo-frontend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max 